## Goal: merge two spectra with different numbers of points

This notebook showcases a few practical ways to **merge (blend)** two spectra even when they contain **different numbers of frequency points**.

You can think of each spectrum as a small table (a Pandas **DataFrame**) with frequency values and their "strength" (power/amplitude). Our goal is to create a smooth transition from one spectrum to the other, even if one spectrum has fewer peaks/points.

First, let's inspect the two example DataFrames and plot them.

In [1]:
import pandas as pd
from audiospylt import detect_dataframe_type

#load data from TSV

df1 = pd.read_csv('../tsv/speech1.tsv', delimiter='\t')
df2 = pd.read_csv('../tsv/conga3.tsv', delimiter='\t')

print("df1:", detect_dataframe_type(df1))
print("df2:", detect_dataframe_type(df2))

df1: {'type': 'single_frame', 'pairs': 41, 'freq_cols': ['Frequency (Hz)'], 'amp_cols': ['Amplitude']}
df2: {'type': 'single_frame', 'pairs': 10, 'freq_cols': ['Frequency (Hz)'], 'amp_cols': ['Amplitude']}

In [2]:
from audiospylt.multiplotter import plot_scatter

# 2D scatter for TSV peak lists.
# Expected columns: 'Frequency (Hz)', 'Amplitude'
# Tip: the axis scaling parameters mirror `py_scripts.dft_analysis.analyze_signal()`.

plot_scatter(
    dfs=[df1, df2],
    mode='markers',
    # Frequency-axis scaling:
    freq_axis_mode='linear',  # 'linear' | 'log' | 'mel' | 'mixed'
    freq_axis_mix=0.5,        # used only when freq_axis_mode='mixed'
    mixed_log_floor_hz=1.0,   # used only when freq_axis_mode='mixed'
    # Amplitude-axis scaling:
    amp_axis_mode='linear',   # 'linear' | 'log' | 'mixed'
    amp_axis_mix=0.5,         # used only when amp_axis_mode='mixed'
    amp_log_floor=1e-12,      # used for 'log'/'mixed'
    # Range handling:
    auto_plot_range=True,
)

The difference is quite large: one spectrum has many more points/peaks than the other.

To build a smooth transition, we need a rule for **pairing points from `df1` with points from `df2`**, even when the two DataFrames have different lengths. Below are a few simple approaches.

## Equal spread

**Idea:** take the DataFrame with fewer points and **duplicate (repeat) its points** until both DataFrames have the same number of rows.

The key detail is *how* we repeat them: we spread the duplicates **evenly**, so every original peak from the smaller DataFrame gets used about the same number of times.

This is simple and intuitive, but it can create "plateaus" where multiple target points come from the exact same source point.

In [3]:
from audiospylt import merge_equal_split
result_equal = merge_equal_split(df1, df2)

display(result_equal)

     freq_data1  amp_data1  freq_data2  amp_data2
0     97.368421   0.000965       31.25   0.000569
1    105.263158   0.005521       31.25   0.000569
2    110.526316   0.002423       31.25   0.000569
3    194.736842   0.001351       75.00   0.000870
4    202.631579   0.003517       75.00   0.000870
5    210.526316   0.007408       75.00   0.000870
6    215.789474   0.005467       75.00   0.000870
7    223.684211   0.004954      127.50   0.000540
8    228.947368   0.003144      127.50   0.000540
9    292.105263   0.001261      127.50   0.000540
10   300.000000   0.003322      127.50   0.000540
11   307.894737   0.007189      127.50   0.000540
12   313.157895   0.007562      238.75   0.003074
13   321.052632   0.007083      238.75   0.003074
14   328.947368   0.005702      238.75   0.003074
15   334.210526   0.003478      238.75   0.003074
16   339.473684   0.002441      321.25   0.002468
17   344.736842   0.001954      321.25   0.002468
18   407.894737   0.001222      321.25   0.002468
19   415.789474   0.001716      321.25   0.002468
20   426.315789   0.001468      321.25   0.002468
21   434.210526   0.001848      393.75   0.000865
22   439.473684   0.001371      393.75   0.000865
23   513.157895   0.000760      393.75   0.000865
24   518.421053   0.000628      393.75   0.000865
25   528.947368   0.000575      398.75   0.000924
26   539.473684   0.000601      398.75   0.000924
27  2239.473684   0.000523      398.75   0.000924
28  2257.894737   0.000643      398.75   0.000924
29  2265.789474   0.000624      518.75   0.000849
30  2278.947368   0.000722      518.75   0.000849
31  2313.157895   0.000725      518.75   0.000849
32  2323.684211   0.000811      518.75   0.000849
33  2331.578947   0.001073      518.75   0.000849
34  2344.736842   0.000752      546.25   0.000567
35  2360.526316   0.001090      546.25   0.000567
36  2381.578947   0.000773      546.25   0.000567
37  2392.105263   0.000645      546.25   0.000567
38  2397.368421   0.000891      600.00   0.001739
39  2952.631579   0.000522      600.00   0.001739
40  3055.263158   0.000553      600.00   0.001739

Let's add a **time** dimension so we can visualize the merge as a *process* (a gradual transition), not just as one final mapping.

In [4]:
from audiospylt import create_time_transition_df

wave_stop_value = 15.0

new_df = create_time_transition_df(
    result_equal, 
    duration=wave_stop_value, 
    scale_amp=True
)
display(new_df)

     freq_start  freq_stop  time_start  time_stop   amp_min   amp_max
0     97.368421      31.25         0.0       15.0  0.127585  0.185020
1    105.263158      31.25         0.0       15.0  0.730145  0.185020
2    110.526316      31.25         0.0       15.0  0.320386  0.185020
3    194.736842      75.00         0.0       15.0  0.178615  0.283141
4    202.631579      75.00         0.0       15.0  0.465142  0.283141
5    210.526316      75.00         0.0       15.0  0.979685  0.283141
6    215.789474      75.00         0.0       15.0  0.722938  0.283141
7    223.684211     127.50         0.0       15.0  0.655112  0.175785
8    228.947368     127.50         0.0       15.0  0.415782  0.175785
9    292.105263     127.50         0.0       15.0  0.166797  0.175785
10   300.000000     127.50         0.0       15.0  0.439353  0.175785
11   307.894737     127.50         0.0       15.0  0.950638  0.175785
12   313.157895     238.75         0.0       15.0  1.000000  1.000000
13   321.052632     238.75         0.0       15.0  0.936703  1.000000
14   328.947368     238.75         0.0       15.0  0.754020  1.000000
15   334.210526     238.75         0.0       15.0  0.459896  1.000000
16   339.473684     321.25         0.0       15.0  0.322809  0.803007
17   344.736842     321.25         0.0       15.0  0.258359  0.803007
18   407.894737     321.25         0.0       15.0  0.161538  0.803007
19   415.789474     321.25         0.0       15.0  0.226979  0.803007
20   426.315789     321.25         0.0       15.0  0.194080  0.803007
21   434.210526     393.75         0.0       15.0  0.244340  0.281394
22   439.473684     393.75         0.0       15.0  0.181338  0.281394
23   513.157895     393.75         0.0       15.0  0.100544  0.281394
24   518.421053     393.75         0.0       15.0  0.083036  0.281394
25   528.947368     398.75         0.0       15.0  0.076028  0.300508
26   539.473684     398.75         0.0       15.0  0.079446  0.300508
27  2239.473684     398.75         0.0       15.0  0.069116  0.300508
28  2257.894737     398.75         0.0       15.0  0.085050  0.300508
29  2265.789474     518.75         0.0       15.0  0.082493  0.276124
30  2278.947368     518.75         0.0       15.0  0.095420  0.276124
31  2313.157895     518.75         0.0       15.0  0.095903  0.276124
32  2323.684211     518.75         0.0       15.0  0.107301  0.276124
33  2331.578947     518.75         0.0       15.0  0.141878  0.276124
34  2344.736842     546.25         0.0       15.0  0.099388  0.184427
35  2360.526316     546.25         0.0       15.0  0.144163  0.184427
36  2381.578947     546.25         0.0       15.0  0.102225  0.184427
37  2392.105263     546.25         0.0       15.0  0.085328  0.184427
38  2397.368421     600.00         0.0       15.0  0.117852  0.565752
39  2952.631579     600.00         0.0       15.0  0.069060  0.565752
40  3055.263158     600.00         0.0       15.0  0.073150  0.565752

In [5]:
from audiospylt.multiplotter import plot_combined
from audiospylt.multiplotter import plot_combined_3d

plot_combined(dfs=[new_df])

plot_combined_3d(
    dfs=[new_df],
    axis_order=("time", "amp", "freq"),
    flip={"amp": True, "time": True},
)

## Cumulative distribution function (CDF)

We can use the **cumulative distribution function (CDF)** idea to merge spectra with *different numbers of points* in a stable way.

Instead of matching rows by "row number" (index), we match by **percentile**:

- For each DataFrame, we sort by frequency and assign every row a percentile from **0% (lowest frequency)** to **100% (highest frequency)**.
- Then we pair points that have the **same percentile**.

This naturally spreads the smaller DataFrame across the full range of the larger one.

Because the mapping is percentile-based, we can also **shape the transition**: with a bias parameter (later called `power`), we can make the merge prefer **lower** or **higher** frequencies.

Next we determine a **valid range** for the bias parameter (so that **every point** from the source DataFrame is still used at least once):

In [6]:
from audiospylt import merge_cdf, merge_cdf_analysis

power_range = merge_cdf_analysis(df1, df2, plot=True)

### How to read the CDF plot (Min Power vs Max Power)

- **x-axis (Frequency)**: the frequencies we get *after mapping* the smaller DataFrame (`freq_data_less`) onto the larger one.
- **y-axis (CDF / percentile)**: for any frequency on the x-axis, y tells you **what fraction of points are at or below** that frequency.
  - Example: y = 0.5 means "half the points are below this frequency" (the median).
- **Why there are two curves**: `Min Power` and `Max Power` are the **most extreme bias values** that still use **all** source points at least once.
  - Staying inside this range means we are *re-weighting* the merge, not *dropping* frequencies.
- **How to interpret the shape**:
  - If a curve rises **quickly** at low frequencies, **many mapped points land in the low-frequency region** (low-frequency bias).
  - If it stays **flat longer** and rises later, **more points get pushed toward higher frequencies** (high-frequency bias).

### Merge using a chosen `power`

Now we merge the two DataFrames using a specific `power` value within the valid range.

In [7]:
result_merge_cdf = merge_cdf(df1, df2, power_factor=1.5, plot=True)

new_df2 = create_time_transition_df(
    result_merge_cdf, 
    duration=15, 
    scale_amp=True
)
display(new_df2)

plot_combined(dfs=[new_df2])

plot_combined_3d(
    dfs=[new_df2],
    axis_order=("time", "amp", "freq"),
    flip={"amp": True, "time": True},
)

     freq_start  freq_stop  time_start  time_stop   amp_min   amp_max
0     97.368421      31.25         0.0       15.0  0.127585  0.185020
1    105.263158      75.00         0.0       15.0  0.730145  0.283141
2    110.526316      75.00         0.0       15.0  0.320386  0.283141
3    194.736842     127.50         0.0       15.0  0.178615  0.175785
4    202.631579     127.50         0.0       15.0  0.465142  0.175785
5    210.526316     127.50         0.0       15.0  0.979685  0.175785
6    215.789474     238.75         0.0       15.0  0.722938  1.000000
7    223.684211     238.75         0.0       15.0  0.655112  1.000000
8    228.947368     238.75         0.0       15.0  0.415782  1.000000
9    292.105263     238.75         0.0       15.0  0.166797  1.000000
10   300.000000     321.25         0.0       15.0  0.439353  0.803007
11   307.894737     321.25         0.0       15.0  0.950638  0.803007
12   313.157895     321.25         0.0       15.0  1.000000  0.803007
13   321.052632     321.25         0.0       15.0  0.936703  0.803007
14   328.947368     321.25         0.0       15.0  0.754020  0.803007
15   334.210526     393.75         0.0       15.0  0.459896  0.281394
16   339.473684     393.75         0.0       15.0  0.322809  0.281394
17   344.736842     393.75         0.0       15.0  0.258359  0.281394
18   407.894737     393.75         0.0       15.0  0.161538  0.281394
19   415.789474     393.75         0.0       15.0  0.226979  0.281394
20   426.315789     398.75         0.0       15.0  0.194080  0.300508
21   434.210526     398.75         0.0       15.0  0.244340  0.300508
22   439.473684     398.75         0.0       15.0  0.181338  0.300508
23   513.157895     398.75         0.0       15.0  0.100544  0.300508
24   518.421053     398.75         0.0       15.0  0.083036  0.300508
25   528.947368     518.75         0.0       15.0  0.076028  0.276124
26   539.473684     518.75         0.0       15.0  0.079446  0.276124
27  2239.473684     518.75         0.0       15.0  0.069116  0.276124
28  2257.894737     518.75         0.0       15.0  0.085050  0.276124
29  2265.789474     518.75         0.0       15.0  0.082493  0.276124
30  2278.947368     518.75         0.0       15.0  0.095420  0.276124
31  2313.157895     546.25         0.0       15.0  0.095903  0.184427
32  2323.684211     546.25         0.0       15.0  0.107301  0.184427
33  2331.578947     546.25         0.0       15.0  0.141878  0.184427
34  2344.736842     546.25         0.0       15.0  0.099388  0.184427
35  2360.526316     546.25         0.0       15.0  0.144163  0.184427
36  2381.578947     546.25         0.0       15.0  0.102225  0.184427
37  2392.105263     546.25         0.0       15.0  0.085328  0.184427
38  2397.368421     600.00         0.0       15.0  0.117852  0.565752
39  2952.631579     600.00         0.0       15.0  0.069060  0.565752
40  3055.263158     600.00         0.0       15.0  0.073150  0.565752

By using a higher `power` value, we tilt the `df1 -> df2` merge toward **higher frequencies**, while still using **all** available frequency pairs (no points are dropped).

## Sigmoid distribution

Next we determine a **valid range** for the sigmoid factor (again, meaning we still use all points at least once):

In [8]:
from audiospylt import merge_sigmoid, merge_sigmoid_analysis

# To analyze and find the valid range (and plot)
valid_range = merge_sigmoid_analysis(df1, df2, plot=True)
print(f"Valid sigmoid range: {valid_range}")

Valid sigmoid range: [np.float64(0.01), np.float64(5.53)]

In [9]:
# To perform the merge
# merged_df = merge_sigmoid(df1, df2) # calculates mean range automatically
# OR with a specific range
result_merge_sigmoid = merge_sigmoid(df1, df2, sigmoid_range=3, plot=True)

In [10]:
new_df3 = create_time_transition_df(
    result_merge_sigmoid, 
    duration=15, 
    scale_amp=True
)
display(new_df3)

plot_combined(dfs=[new_df3])

plot_combined_3d(
    dfs=[new_df3],
    axis_order=("time", "amp", "freq"),
    flip={"amp": True, "time": True},
)

     freq_start  freq_stop  time_start  time_stop   amp_min   amp_max
0     97.368421      31.25         0.0       15.0  0.127585  0.185020
1    105.263158      75.00         0.0       15.0  0.730145  0.283141
2    110.526316      75.00         0.0       15.0  0.320386  0.283141
3    194.736842      75.00         0.0       15.0  0.178615  0.283141
4    202.631579     127.50         0.0       15.0  0.465142  0.175785
5    210.526316     127.50         0.0       15.0  0.979685  0.175785
6    215.789474     127.50         0.0       15.0  0.722938  0.175785
7    223.684211     127.50         0.0       15.0  0.655112  0.175785
8    228.947368     238.75         0.0       15.0  0.415782  1.000000
9    292.105263     238.75         0.0       15.0  0.166797  1.000000
10   300.000000     238.75         0.0       15.0  0.439353  1.000000
11   307.894737     238.75         0.0       15.0  0.950638  1.000000
12   313.157895     238.75         0.0       15.0  1.000000  1.000000
13   321.052632     238.75         0.0       15.0  0.936703  1.000000
14   328.947368     321.25         0.0       15.0  0.754020  0.803007
15   334.210526     321.25         0.0       15.0  0.459896  0.803007
16   339.473684     321.25         0.0       15.0  0.322809  0.803007
17   344.736842     321.25         0.0       15.0  0.258359  0.803007
18   407.894737     321.25         0.0       15.0  0.161538  0.803007
19   415.789474     321.25         0.0       15.0  0.226979  0.803007
20   426.315789     393.75         0.0       15.0  0.194080  0.281394
21   434.210526     393.75         0.0       15.0  0.244340  0.281394
22   439.473684     393.75         0.0       15.0  0.181338  0.281394
23   513.157895     393.75         0.0       15.0  0.100544  0.281394
24   518.421053     393.75         0.0       15.0  0.083036  0.281394
25   528.947368     393.75         0.0       15.0  0.076028  0.281394
26   539.473684     393.75         0.0       15.0  0.079446  0.281394
27  2239.473684     398.75         0.0       15.0  0.069116  0.300508
28  2257.894737     398.75         0.0       15.0  0.085050  0.300508
29  2265.789474     398.75         0.0       15.0  0.082493  0.300508
30  2278.947368     398.75         0.0       15.0  0.095420  0.300508
31  2313.157895     398.75         0.0       15.0  0.095903  0.300508
32  2323.684211     398.75         0.0       15.0  0.107301  0.300508
33  2331.578947     518.75         0.0       15.0  0.141878  0.276124
34  2344.736842     518.75         0.0       15.0  0.099388  0.276124
35  2360.526316     518.75         0.0       15.0  0.144163  0.276124
36  2381.578947     518.75         0.0       15.0  0.102225  0.276124
37  2392.105263     546.25         0.0       15.0  0.085328  0.184427
38  2397.368421     546.25         0.0       15.0  0.117852  0.184427
39  2952.631579     546.25         0.0       15.0  0.069060  0.184427
40  3055.263158     600.00         0.0       15.0  0.073150  0.565752

### What if we go outside the min/max range?

If we go outside the min/max "valid range", we don't just *bias* the mapping anymore -- we start **filtering points out**.

In other words: the mapping becomes so skewed that some frequencies stop being used at all.

Let's see what happens with an intentionally very large sigmoid factor:

In [11]:
extreme_merge_sigmoid = merge_sigmoid(df1, df2, sigmoid_range=300, plot=True)

new_df4 = create_time_transition_df(
    extreme_merge_sigmoid, 
    duration=15, 
    scale_amp=True
)
display(new_df4)

plot_combined(dfs=[new_df4])

plot_combined_3d(
    dfs=[new_df4],
    axis_order=("time", "amp", "freq"),
    flip={"amp": True, "time": True},
)

     freq_start  freq_stop  time_start  time_stop   amp_min   amp_max
0     97.368421      31.25         0.0       15.0  0.127585  0.230409
1    105.263158     321.25         0.0       15.0  0.730145  1.000000
2    110.526316     321.25         0.0       15.0  0.320386  1.000000
3    194.736842     321.25         0.0       15.0  0.178615  1.000000
4    202.631579     321.25         0.0       15.0  0.465142  1.000000
5    210.526316     321.25         0.0       15.0  0.979685  1.000000
6    215.789474     321.25         0.0       15.0  0.722938  1.000000
7    223.684211     321.25         0.0       15.0  0.655112  1.000000
8    228.947368     321.25         0.0       15.0  0.415782  1.000000
9    292.105263     321.25         0.0       15.0  0.166797  1.000000
10   300.000000     321.25         0.0       15.0  0.439353  1.000000
11   307.894737     321.25         0.0       15.0  0.950638  1.000000
12   313.157895     321.25         0.0       15.0  1.000000  1.000000
13   321.052632     321.25         0.0       15.0  0.936703  1.000000
14   328.947368     321.25         0.0       15.0  0.754020  1.000000
15   334.210526     321.25         0.0       15.0  0.459896  1.000000
16   339.473684     321.25         0.0       15.0  0.322809  1.000000
17   344.736842     321.25         0.0       15.0  0.258359  1.000000
18   407.894737     321.25         0.0       15.0  0.161538  1.000000
19   415.789474     321.25         0.0       15.0  0.226979  1.000000
20   426.315789     393.75         0.0       15.0  0.194080  0.350425
21   434.210526     393.75         0.0       15.0  0.244340  0.350425
22   439.473684     393.75         0.0       15.0  0.181338  0.350425
23   513.157895     393.75         0.0       15.0  0.100544  0.350425
24   518.421053     393.75         0.0       15.0  0.083036  0.350425
25   528.947368     393.75         0.0       15.0  0.076028  0.350425
26   539.473684     393.75         0.0       15.0  0.079446  0.350425
27  2239.473684     393.75         0.0       15.0  0.069116  0.350425
28  2257.894737     393.75         0.0       15.0  0.085050  0.350425
29  2265.789474     393.75         0.0       15.0  0.082493  0.350425
30  2278.947368     393.75         0.0       15.0  0.095420  0.350425
31  2313.157895     393.75         0.0       15.0  0.095903  0.350425
32  2323.684211     393.75         0.0       15.0  0.107301  0.350425
33  2331.578947     393.75         0.0       15.0  0.141878  0.350425
34  2344.736842     393.75         0.0       15.0  0.099388  0.350425
35  2360.526316     393.75         0.0       15.0  0.144163  0.350425
36  2381.578947     393.75         0.0       15.0  0.102225  0.350425
37  2392.105263     393.75         0.0       15.0  0.085328  0.350425
38  2397.368421     393.75         0.0       15.0  0.117852  0.350425
39  2952.631579     393.75         0.0       15.0  0.069060  0.350425
40  3055.263158     600.00         0.0       15.0  0.073150  0.704543

Here we get a huge bias toward **center frequencies**.

- Edge frequencies may end up with only **one** connection.
- A small number of center frequencies can end up connected to **many** others.

What happens if we use a sigmoid factor **< 0**?

In [12]:
extreme_negative_merge_sigmoid = merge_sigmoid(df1, df2, sigmoid_range=-10, plot=True)

new_df5 = create_time_transition_df(
    extreme_negative_merge_sigmoid, 
    duration=15, 
    scale_amp=True
)
display(new_df5)

plot_combined(dfs=[new_df5])

plot_combined_3d(
    dfs=[new_df5],
    axis_order=("time", "amp", "freq"),
    flip={"amp": True, "time": True},
)

     freq_start  freq_stop  time_start  time_stop   amp_min   amp_max
0     97.368421     600.00         0.0       15.0  0.127585  0.565752
1    105.263158     398.75         0.0       15.0  0.730145  0.300508
2    110.526316     398.75         0.0       15.0  0.320386  0.300508
3    194.736842     398.75         0.0       15.0  0.178615  0.300508
4    202.631579     398.75         0.0       15.0  0.465142  0.300508
5    210.526316     398.75         0.0       15.0  0.979685  0.300508
6    215.789474     393.75         0.0       15.0  0.722938  0.281394
7    223.684211     393.75         0.0       15.0  0.655112  0.281394
8    228.947368     393.75         0.0       15.0  0.415782  0.281394
9    292.105263     393.75         0.0       15.0  0.166797  0.281394
10   300.000000     393.75         0.0       15.0  0.439353  0.281394
11   307.894737     393.75         0.0       15.0  0.950638  0.281394
12   313.157895     393.75         0.0       15.0  1.000000  0.281394
13   321.052632     393.75         0.0       15.0  0.936703  0.281394
14   328.947368     393.75         0.0       15.0  0.754020  0.281394
15   334.210526     393.75         0.0       15.0  0.459896  0.281394
16   339.473684     393.75         0.0       15.0  0.322809  0.281394
17   344.736842     393.75         0.0       15.0  0.258359  0.281394
18   407.894737     393.75         0.0       15.0  0.161538  0.281394
19   415.789474     393.75         0.0       15.0  0.226979  0.281394
20   426.315789     321.25         0.0       15.0  0.194080  0.803007
21   434.210526     321.25         0.0       15.0  0.244340  0.803007
22   439.473684     321.25         0.0       15.0  0.181338  0.803007
23   513.157895     321.25         0.0       15.0  0.100544  0.803007
24   518.421053     321.25         0.0       15.0  0.083036  0.803007
25   528.947368     321.25         0.0       15.0  0.076028  0.803007
26   539.473684     321.25         0.0       15.0  0.079446  0.803007
27  2239.473684     321.25         0.0       15.0  0.069116  0.803007
28  2257.894737     321.25         0.0       15.0  0.085050  0.803007
29  2265.789474     321.25         0.0       15.0  0.082493  0.803007
30  2278.947368     321.25         0.0       15.0  0.095420  0.803007
31  2313.157895     321.25         0.0       15.0  0.095903  0.803007
32  2323.684211     321.25         0.0       15.0  0.107301  0.803007
33  2331.578947     321.25         0.0       15.0  0.141878  0.803007
34  2344.736842     321.25         0.0       15.0  0.099388  0.803007
35  2360.526316     238.75         0.0       15.0  0.144163  1.000000
36  2381.578947     238.75         0.0       15.0  0.102225  1.000000
37  2392.105263     238.75         0.0       15.0  0.085328  1.000000
38  2397.368421     238.75         0.0       15.0  0.117852  1.000000
39  2952.631579     238.75         0.0       15.0  0.069060  1.000000
40  3055.263158      31.25         0.0       15.0  0.073150  0.185020

The sigmoid curve shape is the same as for a positive factor, but the **direction of the mapping flips**.

Now higher frequencies from `df1` tend to merge into lower frequencies of `df2` (and vice versa).

Because the sigmoid mapping is strongly **center-biased**, we can switch back to the CDF approach when we want a merge that favors the **edges** (very low / very high frequencies):

In [13]:
extreme_merge_cdf = merge_cdf(df1, df2, power_factor=50.5, plot=True)

new_df6 = create_time_transition_df(
    extreme_merge_cdf, 
    duration=15, 
    scale_amp=True
)
display(new_df6)

plot_combined(dfs=[new_df6])

plot_combined_3d(
    dfs=[new_df6],
    axis_order=("time", "amp", "freq"),
    flip={"amp": True, "time": True},
)

     freq_start  freq_stop  time_start  time_stop   amp_min   amp_max
0     97.368421      31.25         0.0       15.0  0.127585  0.327034
1    105.263158     546.25         0.0       15.0  0.730145  0.325985
2    110.526316     546.25         0.0       15.0  0.320386  0.325985
3    194.736842     546.25         0.0       15.0  0.178615  0.325985
4    202.631579     546.25         0.0       15.0  0.465142  0.325985
5    210.526316     546.25         0.0       15.0  0.979685  0.325985
6    215.789474     546.25         0.0       15.0  0.722938  0.325985
7    223.684211     546.25         0.0       15.0  0.655112  0.325985
8    228.947368     546.25         0.0       15.0  0.415782  0.325985
9    292.105263     546.25         0.0       15.0  0.166797  0.325985
10   300.000000     546.25         0.0       15.0  0.439353  0.325985
11   307.894737     546.25         0.0       15.0  0.950638  0.325985
12   313.157895     546.25         0.0       15.0  1.000000  0.325985
13   321.052632     546.25         0.0       15.0  0.936703  0.325985
14   328.947368     546.25         0.0       15.0  0.754020  0.325985
15   334.210526     546.25         0.0       15.0  0.459896  0.325985
16   339.473684     546.25         0.0       15.0  0.322809  0.325985
17   344.736842     546.25         0.0       15.0  0.258359  0.325985
18   407.894737     546.25         0.0       15.0  0.161538  0.325985
19   415.789474     546.25         0.0       15.0  0.226979  0.325985
20   426.315789     546.25         0.0       15.0  0.194080  0.325985
21   434.210526     600.00         0.0       15.0  0.244340  1.000000
22   439.473684     600.00         0.0       15.0  0.181338  1.000000
23   513.157895     600.00         0.0       15.0  0.100544  1.000000
24   518.421053     600.00         0.0       15.0  0.083036  1.000000
25   528.947368     600.00         0.0       15.0  0.076028  1.000000
26   539.473684     600.00         0.0       15.0  0.079446  1.000000
27  2239.473684     600.00         0.0       15.0  0.069116  1.000000
28  2257.894737     600.00         0.0       15.0  0.085050  1.000000
29  2265.789474     600.00         0.0       15.0  0.082493  1.000000
30  2278.947368     600.00         0.0       15.0  0.095420  1.000000
31  2313.157895     600.00         0.0       15.0  0.095903  1.000000
32  2323.684211     600.00         0.0       15.0  0.107301  1.000000
33  2331.578947     600.00         0.0       15.0  0.141878  1.000000
34  2344.736842     600.00         0.0       15.0  0.099388  1.000000
35  2360.526316     600.00         0.0       15.0  0.144163  1.000000
36  2381.578947     600.00         0.0       15.0  0.102225  1.000000
37  2392.105263     600.00         0.0       15.0  0.085328  1.000000
38  2397.368421     600.00         0.0       15.0  0.117852  1.000000
39  2952.631579     600.00         0.0       15.0  0.069060  1.000000
40  3055.263158     600.00         0.0       15.0  0.073150  1.000000

As you can see, `df2` gets reduced to only the **two highest** and the **lowest** frequency.

Similarly, we can use a **negative** `power` factor with the CDF. Strictly speaking this is not the "standard" interpretation of a CDF, but in this notebook it's implemented as a **mirrored** mapping to flip the bias.

In [17]:
extreme_negative_merge_cdf = merge_cdf(df1, df2, power_factor=-50.5, plot=True)

new_df7 = create_time_transition_df(
    extreme_negative_merge_cdf, 
    duration=15, 
    scale_amp=True
)
display(new_df7)

plot_combined(dfs=[new_df7])

plot_combined_3d(
    dfs=[new_df7],
    axis_order=("time", "amp", "freq"),
    flip={"amp": True, "time": True},
)

     freq_start  freq_stop  time_start  time_stop   amp_min   amp_max
0     97.368421     600.00         0.0       15.0  0.127585  1.000000
1    105.263158      75.00         0.0       15.0  0.730145  0.500468
2    110.526316      75.00         0.0       15.0  0.320386  0.500468
3    194.736842      75.00         0.0       15.0  0.178615  0.500468
4    202.631579      75.00         0.0       15.0  0.465142  0.500468
5    210.526316      75.00         0.0       15.0  0.979685  0.500468
6    215.789474      75.00         0.0       15.0  0.722938  0.500468
7    223.684211      75.00         0.0       15.0  0.655112  0.500468
8    228.947368      75.00         0.0       15.0  0.415782  0.500468
9    292.105263      75.00         0.0       15.0  0.166797  0.500468
10   300.000000      75.00         0.0       15.0  0.439353  0.500468
11   307.894737      75.00         0.0       15.0  0.950638  0.500468
12   313.157895      75.00         0.0       15.0  1.000000  0.500468
13   321.052632      75.00         0.0       15.0  0.936703  0.500468
14   328.947368      75.00         0.0       15.0  0.754020  0.500468
15   334.210526      75.00         0.0       15.0  0.459896  0.500468
16   339.473684      75.00         0.0       15.0  0.322809  0.500468
17   344.736842      75.00         0.0       15.0  0.258359  0.500468
18   407.894737      75.00         0.0       15.0  0.161538  0.500468
19   415.789474      75.00         0.0       15.0  0.226979  0.500468
20   426.315789      75.00         0.0       15.0  0.194080  0.500468
21   434.210526      31.25         0.0       15.0  0.244340  0.327034
22   439.473684      31.25         0.0       15.0  0.181338  0.327034
23   513.157895      31.25         0.0       15.0  0.100544  0.327034
24   518.421053      31.25         0.0       15.0  0.083036  0.327034
25   528.947368      31.25         0.0       15.0  0.076028  0.327034
26   539.473684      31.25         0.0       15.0  0.079446  0.327034
27  2239.473684      31.25         0.0       15.0  0.069116  0.327034
28  2257.894737      31.25         0.0       15.0  0.085050  0.327034
29  2265.789474      31.25         0.0       15.0  0.082493  0.327034
30  2278.947368      31.25         0.0       15.0  0.095420  0.327034
31  2313.157895      31.25         0.0       15.0  0.095903  0.327034
32  2323.684211      31.25         0.0       15.0  0.107301  0.327034
33  2331.578947      31.25         0.0       15.0  0.141878  0.327034
34  2344.736842      31.25         0.0       15.0  0.099388  0.327034
35  2360.526316      31.25         0.0       15.0  0.144163  0.327034
36  2381.578947      31.25         0.0       15.0  0.102225  0.327034
37  2392.105263      31.25         0.0       15.0  0.085328  0.327034
38  2397.368421      31.25         0.0       15.0  0.117852  0.327034
39  2952.631579      31.25         0.0       15.0  0.069060  0.327034
40  3055.263158      31.25         0.0       15.0  0.073150  0.327034

### Export

Save the result as **TSV** (including the time dimension, if present).

In [18]:
from audiospylt.io_utils import save_df_tsv

# # Save the amp/freq table (peaks_df) for reuse.
save_df_tsv(new_df7, "../tsv/merged_test.tsv")

Data saved successfully to c:\Users\egorp\Nextcloud\code\public_repos\audiospylt\tutorials_tech\../tsv/merged_test.tsv at 2026-01-31 14:53:35.279400.

'../tsv/merged_test.tsv'